### PR TITLE
Add support for .NET Core

### LINKED ISSUE #48: Add support for .NET Core

### PR DESCRIPTION
**Pull request by japarson**
Fixes #48

### Strategy
I'm adding dependency support for .NET Core and .NET 5.0+ (Core, Asp, and Desktop). We can see which .NET Core runtimes are already installed by using the CLI NetCoreCheck tool, which needs to be shipped with the installer if any .NET Core/.NET 5.0+ products are selected. The tool can determine which .NET Core/.NET 5.0+ runtimes are installed and we can check the result using the return code.

### Demo
In the gif below, I download and install the .NET 5.0 Windows Desktop Runtime (x64).
dotnet50desktop

### CODE REVIEW

**Comment by domgho** [comment]
Thanks. Please try to make it more uniform to existing dependencies (see vcredist2013.iss):

1. Indent with 1 tab instead of 4 spaces
2. Check for `if (not IsIA64()) then begin` since there are no itanium URLs
3. Define x86 URL/reg without x86 name suffix
4. Define x86 URL before x64 URL
5. Use `GetString(XXX_url, XXX_url_x64, '')` for urls instead of variable
6. Remove `WOW6432Node\` from registry paths. See https://stackoverflow.com/questions/46258689/writing-32-64-bit-specific-registry-key-in-inno-setup

**Comment by japarson** [comment]
Thank you for the feedback, @domgho. 

After talking with my team, they brought up the issue that checking registry values is not good enough for [detecting .NET Core runtime installations](https://github.com/dotnet/runtime/issues/36479). A member of my team has developed a program that can properly check if a certain runtime installation is installed (.net core 3.0+ only). So if users add a dependency for these runtimes, we'll have to download the tool first before checking if they're already installed. For versions lower than 3.0, checking the registry values is our only option.

I'm aadding the following todos based on our conversations:
- [ ] Integrate NetCoreChk tool for .NET Core versions > 3.0.
- [ ] Remove dependency support for non-LTS .NET Core versions.
- [ ] Add support for ASP.NET Core.
- [ ] Differentiate between core runtime and desktop runtime.

**Comment by japarson** [comment]
@domgho I addressed your feedback in the recent update:
- [x] Indent with 1 tab instead of 4 spaces
- [x] Check for if (not IsIA64()) then begin since there are no itanium URLs
- [x] Define x86 URL/reg without x86 name suffix
- [x] Define x86 URL before x64 URL
- [x] Use GetString(XXX_url, XXX_url_x64, '') for urls instead of variable

This feedback is no longer relevant, as we changed the way that we check for .NET Core/.NET 5.0+ runtime installations:
- [ ] Remove WOW6432Node\ from registry paths. See https://stackoverflow.com/questions/46258689/writing-32-64-bit-specific-registry-key-in-inno-setup

Please see the updated PR description with a new demo of the behavior and let me know if you have more feedback.

**Comment by MSLukeWest** [comment]
Two branding comments on the titles you're using:

1. Right now you differentiate architecture by just adding "64-bit" to the end of the x64 version (Example: ".NET Core Runtime 3.1" / ".NET Core Runtime 3.1 64-Bit").  I think you should explicitly mention the architecture even in the x86 case (Example: ".NET Core Runtime 3.1 (x86)" / ".NET Core Runtime 3.1 (x64)") like they do on the runtimes download page.  The way you have the title now may lead users to think there aren't platform specific versions of the runtime, especially since the .NET Framework installer wasn't platform specific.
2. You should probably add the word "Preview" to the .NET 5 title to indicate it hasn't been released yet.

**Comment by domgho** [comment]
Thanks @japarson, the biggest issue I have is the reliance on a third-party tool to detect if .NET is installed.

Can't we do what the tool does? What does it even do? Is there really no official way using the registry to detect if .NET is installed especially for the upcoming .NET 5?

For the Visual C++ Redistributable we also couldn't use the registry and instead had to rely on querying the product using MSI but that at least did not require using a separate executable so maybe something similar can be done here.

However if there is really no sensible way to get rid of netcorecheck.exe then I think it should not be downloaded but instead be shipped with the setup and extracted before checking if .NET 5/netcore is installed using `ExtractTemporaryFile('file.exe')`. See directxruntime.iss

@MSLukeWest Good points. Regarding the first point: We also do the same for other products so this probably needs to be revised separately in general

**Comment by Jaex** [comment]
> the biggest issue I have is the reliance on a third-party tool to detect if .NET is installed.

I also had same concerns when I saw this PR. It feels so wrong to download executable just to be able to check is another dependency should be downloaded. I don't understand why what that executable does can't be implemented directly in script. Also is that executable open source, can we see what it does exactly?

**Comment by MSLukeWest** [comment]
Regarding the NetCoreCheck tool, the source is in a github repro that's Private for now but will be public soon (@NikolaMilosavljevic is working on that).  Once that happens you'll be able to view the source here: https://github.com/dotnet/deployment-tools/tree/master/src/clickonce/native/projects/NetCoreCheck

See this issue for more details about the tool: https://github.com/dotnet/runtime/issues/36479.  You'll see some of the rationale for it as well the approach being suggested by members of the .NET runtime team.  In short, acquisition issues with the .NET Core 3.1 runtime installers made reliable detection using just registry/file checks near impossible, so the .NET team suggested this approach.

Also, if it helps add confidence in the tool, the Visual Studio bootstrapper packages for .NET Core 3.1 used by Installer Projects (https://marketplace.visualstudio.com/items?itemName=visualstudioclient.MicrosoftVisualStudio2017InstallerProjects) that will be included with the upcoming VS 2019 Update 7 will rely on this tool as well.  We developed it with the intention of sharing it with other installer technologies as necessary.

**Comment by japarson** [comment]
@domgho I modified the scripts so that the NetCoreCheck tool must be shipped with installers instead of downloaded. I also fixed up the product titles and added some documentation about the NetCoreCheck tool. Let me know if you have any other feedback.

**Comment by domgho** [comment]
@japarson Thanks I have just merged this PR and cleaned up the code. Please let me know if this is working as intended now.

**Comment by japarson** [comment]
@domgho Just tested your changes. It's working! Thank you for working with me on this issue. Your guidance was very helpful. 👍

**Pull request closed without merging**
